apiVersion: apps/v1
kind: Deployment
metadata:
  name: ht1-deployment
  namespace: so1-ht1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ht1-app
  template:
    metadata:
      labels:
        app: ht1-app
    spec:
      containers:
      - name: ht1-app-container
        image: jajsivianc/ht1:1.0.2
        ports:
        - containerPort: 8080 
        resources:
          limits:
            cpu: "0.1"
            memory: "40Mi"