apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ht1-ingress
  namespace: so1-ht1
  labels:
    name: ht1-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: 34.16.87.214.nip.io
    http:
      paths:
      - path: /agronomy
        pathType: Prefix
        backend:
          service:
            name: ht1-service
            port:
              number: 8080
