services:
  python_service:
    build: ./
    container_name: python_container
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/code/logs
      - ./imgs:/code/imgs
    command: ["fastapi", "run", "main.py", "--port", "8000"]
