apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-node-engineering
  namespace: so1-proyecto2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: engineering-deployment
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 35

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-node-agronomy
  namespace: so1-proyecto2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: agronomy-deployment
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 35


